package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/RainDragonSk8er/AOC2025/pkg/table"
)

func main() {
	// Load Theme
	theme := table.Theme{
		Bar: table.BarConfig{Filled: "#", Empty: "."},
		Emoticons: []table.EmoticonConfig{
			{Threshold: 0, Icon: "(╯°□°)╯︵ ┻━┻"},
		},
	}
	themeData, err := os.ReadFile("config/theme.json")
	if err == nil {
		json.Unmarshal(themeData, &theme)
	} else {
		log.Println("Warning: config/theme.json not found, using default theme")
	}

	var sb strings.Builder
	sb.WriteString("# Theme Preview\n\n")
	sb.WriteString("This file is auto-generated by `cmd/preview`. Use it to verify your theme settings.\n\n")
	sb.WriteString("```diff\n")
	sb.WriteString("! --- Theme Gallery ---\n\n")

	maxStars := 24
	barWidth := 24

	// Iterate through emoticons to show each stage
	for _, emo := range theme.Emoticons {
		stars := emo.Threshold
		if stars > maxStars {
			stars = maxStars
		}

		// Progress Bar
		filled := stars
		empty := barWidth - filled
		bar := strings.Repeat(theme.Bar.Filled, filled) + strings.Repeat(theme.Bar.Empty, empty)

		sb.WriteString(fmt.Sprintf("+ Level: %d Stars\n", stars))
		sb.WriteString(fmt.Sprintf("! [%s] %d Stars %s\n\n", bar, stars, emo.Icon))
	}
	sb.WriteString("```\n")

	if err := os.WriteFile("THEME_PREVIEW.md", []byte(sb.String()), 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("Generated THEME_PREVIEW.md")
}
